#!/bin/bash
# i will start by making a variable for the opening code.
# System Report
system_report="System Report generated by $(whoami), $(date)"
# now i will
# Display system report
echo "System Report"
echo "---------------------"
echo "$system_report"
echo "---------------------"
# no i will show
# System Information
echo "System Information"
echo "---------------------"
echo "Hostname: $(hostname)"
echo "OS: $(source /etc/os-release && echo $PRETTY_NAME)"
echo "Uptime: $(uptime -p)"
echo "---------------------"
# when i need to show
# Hardware Information, i will
# make some cat uses too, to ensure i use every knowledge taken.
echo "Hardware Information"
echo "---------------------"
echo "CPU:"
cat /proc/cpuinfo | grep "model name" | head -n 1 | awk -F': ' '{print $2}'
echo "Speed:"
sudo lshw -class processor | awk '/description: CPU/{p=1} p && /size:/{print $2; exit}'
sudo lshw -class processor | awk '/description: CPU/{p=1} p && /capacity:/{print $2; exit}'
echo "RAM:"
cat sudo lshw -short -C memory | grep -i 'system memory' | awk '{print $3}'
echo "Disks:"
lsblk -o NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6}'
echo "Video card:"
lspci | grep -i "VGA" | awk -F': ' '{print $2}' | uniq
echo "---------------------"

# the Network Information section is easy then others, if we leave the network interface.
echo "Network Information"
echo "---------------------"
echo "FQDN: $(hostname -f)"
echo "Host Address: $(hostname -I)"
echo "Gateway IP: $(ip route | awk '/default/ {print $3}')"
echo "DNS Server:"
cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}'
echo "Network Interface Information:"
sudo lshw -class network | grep -E 'description|product|vendor|physical id|logical name' | awk -F ':' '{print $1 ": " $2}'
echo "IP Address:"
ip -o addr show | awk '$3 == "inet" {print $4}'
echo "---------------------"
# in the system status section, i will conclude direct commands to operate
# System Status
echo "System Status"
echo "---------------------"
echo "Users Logged In:"
who | awk '{print $1}' | sort | uniq | paste -s -d ','
echo "Disk Space:"
df -h
echo "Process Count:"
ps -e | wc -l
echo "Load Averages:"
uptime | awk -F'[a-z]:' '{print $2}'
echo "Memory Allocation:"
free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}'
echo "Listening Network Ports:"
ss -tuln | awk 'BEGIN {print "State\tRecv-Q\tSend-Q\tLocal Address:Port\tPeer Address:Port"} /LISTEN/ {print $1 "\t" $2 "\t" $3 "\t" $4 "\t\t" $5}'
echo "UFW Rules:"
sudo ufw status numbered | grep -v 'Status: active'
echo "---------------------"
# this ends the script and shows proper output by dotted lines.
